### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by mohammadhamzehloui** [Maks3w/SwaggerAssertions#1]
Hi 
I tried to install it, based on your documentation, by using : 
composer require Maks3w/SwaggerAssertions
it then asks for entering the version, below is the message:

Please provide a version constraint for the Maks3w/SwaggerAssertions requirement :
I tried 0.1.2, and some other like 0.1.1
 
and below is the error that I get :
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package maks3w/swaggerassertions could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

I also tried to clone the project and run it locally, but then I get the below error:

  [RuntimeException]
  Could not load package fr3d/swagger-assertions in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^0.3.1: Invalid ver
  sion string "^0.3.1"

  [UnexpectedValueException]
  Could not parse version constraint ^0.3.1: Invalid version string "^0.3.1"

**Comment by Maks3w** [comment]
Please update your composer version and tell me if works.

**Comment by mohammadhamzehloui** [comment]
Updated composer:
You are already using composer version a32c91914558a3ff293d83f7b99c49f4a7931798.

Run:

composer require Maks3w/SwaggerAssertions

error that I get now:

[InvalidArgumentException]
  Could not find package Maks3w/SwaggerAssertions at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by Maks3w** [comment]
Sorry package name is wrong.  use `fr3d/swagger-assertions`

**Comment by mohammadhamzehloui** [comment]
Yup, it worked, thanks a lot.
