### ISSUE TITLE
Tests are always pass

### ISSUE THREAD

**Issue by SergeC** [Maks3w/SwaggerAssertions#10]
Tests are always pass. Even if I manually corrupt `fixtures/pet_store.json` tests are still pass. Steps to reproduce:

1. cd ~/Desktop
2. git clone https://github.com/Maks3w/SwaggerAssertions.git
3. cd SwaggerAssertions
4. composer install
5. phpunit examples/PhpUnit/LocalFileTest.php
6. Manually corrupt `fixtures/pet_store.json` -> `#/definitions/Pet` -> set `properties.category` to `properties.catego*1*ry`
7. phpunit examples/PhpUnit/LocalFileTest.php Test passes but should fail.

Is any way to fix it?

**Comment by Maks3w** [comment]
This project does not validate your swagger definition is syntax/grammar correct.

What this project do is assert your implementation (your api server) match with your documentation (swagger definition)
