### ISSUE TITLE
json-schema breaks for URI now

### ISSUE THREAD

**Issue by untaken** [Maks3w/SwaggerAssertions#11]
It looks like justinrainbow/json-schema has recently been updated and it now breaks SwaggerAssertions, if you try and pass SchemaManager a URL, like so:

$this->schemaManager = new SchemaManager('http://petstore.swagger.io/v2/swagger.json');

This commit has caused the recent issue:

https://github.com/justinrainbow/json-schema/commit/780dd6f45f86eadfcebee13d22a3771391bbb2e1

If you try and use a URL now, it will fail on:

 ./vendor/justinrainbow/json-schema/src/JsonSchema/Uri/Retrievers/FileGetContents.php

 30         if (!file_exists($uri)) {
 31             throw new ResourceNotFoundException('JSON schema not found at ' . $uri);
 32         }

A temporary fix is to tell SwaggerAssertions composer.json to use 2.0.2 of justinrainbow/json-schema, but probably not the best solution long term?

**Comment by Maks3w** [comment]
Seems we need to do now `(new UriRetriever)->setUriRetriever(new Curl())`

Could you try?

**Comment by untaken** [comment]
This does not work as expected, I am guessing I am doing something wrong though tbh.

**Comment by Maks3w** [comment]
We can write a custom UriRetriever, open an issue to json-schema project or constraint the version

**Comment by untaken** [comment]
Thanks. I'll constraint the version for the time being.
