### ISSUE TITLE
How to check whether request or response contain undescribed parameters?

### ISSUE THREAD

**Issue by everhardt** [Maks3w/SwaggerAssertions#12]
The test functions currently do not fail when the request and/or response contain parameters that are not defined in the swagger definition. I'd like to check this, as it is an indication that my swagger-file is outdated. How could I add this?

**Comment by Maks3w** [comment]
If you have a question about swagger please schema please refer to swagger project or ask to a Q&A site like stackoverflow.

Hint: "additionalProperties": false

**Comment by everhardt** [comment]
Cool, thanks! I missed that in the [specs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject)

**Comment by mnapoli** [comment]
Do you confirm that we have to add `additionalProperties` to all of our definitions? That seems tedious 😓

**Comment by Maks3w** [comment]
@mnapoli I think the correct everyone follows the swagger specification. If you have an argument about why I should deviate from the standard please share with us.

**Comment by mnapoli** [comment]
I understand this is a tough situation: on one hand this repository is about swagger assertions. So it makes sense not to deviate from the standard.

But at the same time that makes the validation extremely lax. And as a result the assertions aren't that useful. For example they can't help detect new fields that are missing from the documentation, or fields that were provided in extra in the tests.

**Comment by Maks3w** [comment]
I'm not sure to understand. I currently detect both situations (extra fields or missing fields) playing with `additionalProperties: False` along the `required` fields array.
