### ISSUE TITLE
How to check non-JSON requests with SymfonyAssertsTrait

### ISSUE THREAD

**Issue by everhardt** [Maks3w/SwaggerAssertions#13]
In the function `assertResponseMatch` of SymfonyAssertsTrait, it looks like it assumes that the body is always json, given that it is always calling `json_decode`.

For the oauth service I use regular POST parameters, which are not available under
`$request->getContent()`
but under 
`$request->request->all()`

Is SwaggerAssertions also capable of checking these requests?

**Comment by Maks3w** [comment]
Pull requests are welcome.

**Comment by everhardt** [comment]
Just looked into it for about 30 mins, but ran into the fact that the underlying json-schema package doesn't support formData-parameters. So for now, I'll leave it as it is.
