### ISSUE TITLE
Strict mode for comparison

### ISSUE THREAD

**Issue by FloKnapp** [Maks3w/SwaggerAssertions#19]
Currently there is no strict mode in comparison of the response body and the given definition. This results in the strange behavior, that the test goes green, even if there are more parameters in response as defined. The strict mode should check the amount of given parameters against the amount of parameters in definition.

**Comment by s3m3n** [comment]
It's the same thing here... There is no sense of tests if they don't check if all required fields of definitions are available in response. Happy I'm not alone while I spent few hours on it already debugging what's happening inside validators. Still don't know where specific problematic line is.

Simple definition in swagger.conf with :

```json
    "definitions": {
        "User": {
            "required": [
                "email",
                "name",
                "surname",
                "dupa"
            ],
            "properties": {
                "email": {
                    "description": "User e-mail address",
                    "type": "string"
                },
                "name": {
                    "description": "User name",
                    "type": "string"
                },
                "surname": {
                    "description": "User surname",
                    "type": "string"
                },
                "dupa": {
                    "type": "string"
                }
            }
        }
    }
```

Where `dupa` is special field not existing anywhere.

Now we run like in the examples:

```php
$this->assertResponseMatch($response, self::$schemaManager, '/v1/user/1', 'get');
```

Test ends green. After debugging I can see that `JsonSchemaConstraint.php::matches` has correct values of response to match:

```log
/vendor/fr3d/swagger-assertions/src/PhpUnit/JsonSchemaConstraint.php:48<pre>stdClass Object
(
    [status] => success
    [data] => stdClass Object
        (
            [email] => ...
            [user_id] => 1
            [name] => Michał
            [surname] => Semeniuk
            [avatar] => 
        )

)
</pre>
```

and `expectedSchema`:

```log
/vendor/fr3d/swagger-assertions/src/PhpUnit/JsonSchemaConstraint.php:49<pre>stdClass Object
(
    [$ref] => #/definitions/User
)
```

and it returns that response is valid. It seems that required fields of definitions are not parsed under validators. To be honest whole response should be invalid as API returns data in Jsend formatting and User is available under `data` not in root so all of required fields are expected to be missing.

**Comment by Maks3w** [comment]
@FloKnapp Your issue is the same of https://github.com/Maks3w/SwaggerAssertions/issues/12

Hint: "additionalProperties": false


@s3m3n Please describe your problem in a different issue and provide the response payload.
