### ISSUE TITLE
Mapper fails to recognise endpoint with variable file extension

### ISSUE THREAD

**Issue by corleonis** [Maks3w/SwaggerAssertions#22]
Let me say first, great library and thank you for providing/supporting it!

I have following endpoint: `https://site.com/v1/company/us/123456.json` and that mapps to following Swagger spcification: `/v1/company/{country}/{companyId}.{format}` where format can be either XML or JSON.

So my problem is that the code sees the path as like there is no file extension and the `companyId=123456.json` because the `.` is deemed as a valid character and not a separator as is the case with `/`

So my question is there any way around that problem?

**Comment by Maks3w** [comment]
@corleonis This seems to be an issue with the underline URI Template library.

Check https://github.com/rize/UriTemplate
