### ISSUE TITLE
Dependency clash with json_schema

### ISSUE THREAD

**Issue by SAThomsen** [Maks3w/SwaggerAssertions#28]
Hey there, this looks like just the thing I was looking for. 
However, the tie to the outdated version of justinrainbow/json_schema is preventing me from using the package.

I took a closer look at the code and by just replacing the class RefResolver in SchemaManager with SchemaStorage, I was able to make all but 11 tests pass with the newest version of json_schema(5.0.2).

The remaining failing tests seem to be related to the document tree not beeing traversed correctly, however, I'm unsure of how to fix it.
Is there any reason why the package is pinned at 2.0.1 or is it viable to keep pushing for this?

**Comment by Maks3w** [comment]
You have point the reasons.

**Comment by SAThomsen** [comment]
The question is if I fix it will we upgrade to 5.0.2. Or is there something I have missed that prevents that update?

**Comment by Maks3w** [comment]
To be honest, yes and no. I could release it as 0.9 but it can't be reverted on 0.10 if the number clashes get bigger or affect to popular dependencies.

**Comment by bsacharski** [comment]
@Maks3w I'm in similar situation to @SAThomsen - we would like to use swagger assertions, and at the same time we would like to use new json-schema versions of the library. Right now the version clash make it impossible though.

**Comment by sanderlissenburg** [comment]
I'm having the same problem. I would like to use your library, but if this dependency clash is not resolved I can and will not use it.

**Comment by andreygrehov** [comment]
@Maks3w any plans to upgrade the json-schema dependency?
