### ISSUE TITLE
assertResponseBodyMatch ignores definition

### ISSUE THREAD

**Issue by pachico** [Maks3w/SwaggerAssertions#31]
Hi there.
I am failing at validating that the response body matches the definition defined in swagger definition.
I used your very same example.
For the sake of reproducing it, here's what I did:
I requested
```php
$request = new Request('GET', 'http://petstore.swagger.io/v2/pet/findByStatus?status=available');
```
which, according to http://petstore.swagger.io/v2/swagger.json, the 200 response schema is:
```json
"schema": {
    "type": "array",
    "items": {
        "$ref": "#/definitions/Pet"
    }
}
```
Where `Pet` is:
```json
"Pet": {
    "type": "object",
    "required": ["name", "photoUrls"],
    "properties": {
        "id": {
            "type": "integer",
            "format": "int64"
        },
        "category": {
            "$ref": "#/definitions/Category"
        },
        "name": {
            "type": "string",
            "example": "doggie"
        },
        "photoUrls": {
            "type": "array",
            "xml": {
                "name": "photoUrl",
                "wrapped": true
            },
            "items": {
                "type": "string"
            }
        },
        "tags": {
            "type": "array",
            "xml": {
                "name": "tag",
                "wrapped": true
            },
            "items": {
                "$ref": "#/definitions/Tag"
            }
        },
        "status": {
            "type": "string",
            "description": "pet status in the store",
            "enum": ["available", "pending", "sold"]
        }
    },
    "xml": {
        "name": "Pet"
    }
}
```
Test gives OK.
Now, if I were to change the `name` property to `integer` it should fail, but it doesn't.

```json
"name": {
    "type": "integer"
},
```
Is this the intended behaviour? What is then the library validating?
I'm running php 7.1.

Cheers

**Comment by Maks3w** [comment]
Sorry but `Test gives OK` against what payload?

**Comment by pachico** [comment]
Against the response body that the request returns: http://petstore.swagger.io/v2/pet/findByStatus?status=available.
It's a public api, good to try some parts of Swagger (not all).

**Comment by Maks3w** [comment]
Please provide a link to a self content gist with the minimum amount of data for to reproduce the issue. thx.

**Comment by pachico** [comment]
It is actually your very same example but loading the yaml from a local file with a slight change (I wanted to see if it worked as expected).
However, from this I get it is expected to validate the response payload against the swagger definitions as well, which is good.

I'll try to provide you gist with it soon.

**Comment by Maks3w** [comment]
That external resource contains mutable data. Please provide a reproducible case with fixed data.

**Comment by dwgebler** [comment]
This is a real issue, I thought I might be using your library incorrectly but it doesn't actually validate any JSON schema definitions. In AssertsTrait, for my API, I inspect $bodySchema and find it is a stdClass with $type='object' and $$ref='#definitions/TestApiThing'

It doesn't resolve the definition. As long as the body response is any obejct, assertResponseBodyMatch will pass. If I change my API to spit out a JSON list [1,2,3] the assert will fail, correctly identifying a list is not an object. But if my API returns {"bad":"not valid"} for example, the assert will pass even though the JSON schema definitions for TestApiThing requires a particular structure.

**Comment by xeras** [comment]
The same issue appears with request parameter definitions. It doesn't resolve "$ref" and just throw an exception with the message 'Missing "in" field in Parameter Object'.

**Comment by xeras** [comment]
I think you have to create the schema manager with provided factory.

**Wrong:**
`$schemaManager = new SchemaManager(json_decode(file_get_contents($filePath)));`

**Correct:**

`$schemaManager = SchemaManager::fromUri('file://' . filePath);`

This way the JsonSchema\RefResolver will resolve the missing definitions.
