### ISSUE TITLE
Nullable extension not taken into consideration ?

### ISSUE THREAD

**Issue by El-Sam** [Maks3w/SwaggerAssertions#33]
Hi, I have this nullable property : 
```json
"archived": {
    "type": "integer",
    "minimum": 0,
    "x-nullable": true
},
```

when I'm testing , it fails when the property is null, here's the assertion error message : 
`[archived] NULL value found, but an integer is required`

is it due to swagger-assertions not supporting vendor extensions or what ? any help.

**Comment by Maks3w** [comment]
Obviouslly vendor extensions behavior is not defined so if you wanna use them you've to *extend* the tools for support them.
