### ISSUE TITLE
Pattern mathing in URLs

### ISSUE THREAD

**Issue by floogman** [Maks3w/SwaggerAssertions#35]
Hi, 

Do you have a suggestion how to handle URLs that use variables and look similar to URLs that have paths that kind of match those variables, e.g.

/some/path/{var}
vs.
/some/path/non-var

In our case {var} is a placeholder for an id with only digits. The application routing allows to make this distinction. However when validating the second path's URL also matches the first path (when not considering pattern matching). Then the swagger assertion fails because the second path's response is validated against the specification of the first URL.

**Comment by Maks3w** [comment]
This seems to be an issue with the underline URI Template library.

Check https://github.com/rize/UriTemplate

**Comment by floogman** [comment]
The function 'findPathInTemplates' only uses the URI Template library to parse the URI. The issue is that it returns the _first_ possible matching URI, not necessarily the _best_ matching URI. The best matching URI could also consider possible regex patterns specified for the parameter in the swagger.json, which it currently does not. 
I was considering overriding the 'findPathInTemplates' method, which is not so straight forward, since it would require inheriting from the SchemaManager class. Also, if I were eventually to create a pull request, I would also prefer that the used URI parser class could be set externally, or the 'findPathInTemplates' method executed externally, of the methods of the 'Psr7AssertsTrait' trait.

**Comment by Maks3w** [comment]
Try it.
