### ISSUE TITLE
Query parameters to lower case

### ISSUE THREAD

**Issue by roelywoely** [Maks3w/SwaggerAssertions#36]
This code maps query parameters to lower case: https://github.com/Maks3w/SwaggerAssertions/blob/master/src/PhpUnit/ResponseHeadersConstraint.php#L23

Why? If you have a case sensitive query parameter in your Swagger definitions, it will fail the assertion because it's being checked against a lower case query parameter.

**Comment by Maks3w** [comment]
The code that you have highlighted is for headers. Following headers standard they are case insensitive.

**Comment by roelywoely** [comment]
Sorry, I added the wrong link.
https://github.com/Maks3w/SwaggerAssertions/blob/master/src/PhpUnit/RequestQueryConstraint.php#L45

**Comment by roelywoely** [comment]
I created a pull request: https://github.com/Maks3w/SwaggerAssertions/pull/38
