### ISSUE TITLE
Upgrade dependency "justinrainbow/json-schema"

### ISSUE THREAD

**Issue by xeras** [Maks3w/SwaggerAssertions#42]
Please upgrade `"justinrainbow/json-schema": "^2.0.1"` to current version is 5.1.2.
Without an update we can't use necessary features like type coercion.

**Comment by xeras** [comment]
Why do you close this issue?

**Comment by Maks3w** [comment]
https://github.com/Maks3w/SwaggerAssertions/issues/28 ?
