### ISSUE TITLE
InvalidSchemaMediaTypeException on schema content type: "application/json; charset=UTF-8"

### ISSUE THREAD

**Issue by benjamin-rtblw** [Maks3w/SwaggerAssertions#44]
Hi,

When downloading my JSON schema, we send the content-type "application/json; charset=UTF-8" that seems to be a valid content-type. So why do I get the error message : JsonSchema\Exception\InvalidSchemaMediaTypeException: Media type application/schema+json expected ?

I'm using the version 0.8.2 of SwaggerAssertions on PHP7

**Comment by Maks3w** [comment]
`SchemaManager::fromUri` is provided as convenience but I don't support it as is not required.

Customize your own way for construct SchemaManager
