### ISSUE TITLE
Dependency on phpunit instead of symfony/validator

### ISSUE THREAD

**Issue by bkielbasa** [Maks3w/SwaggerAssertions#46]
I have noticed that you added phpunit/phpunit to require section in composer.json. I think it should be changed and the code should be rebuilt to use an alternative like symfony/validator and it's Constraints instead of using phpunit's version.

The reason I would change is that all dev libraries (phpunit is one of them) has no security guarantee so it should not be used in production env at all.

**Comment by Maks3w** [comment]
Why are you using SwaggerAssertions as a prod library?
