### ISSUE TITLE
Different implementations of SymfonyAssertsTrait::assertRequestMatch() and SymfonyAssertsTrait::assertResponseMatch() methods

### ISSUE THREAD

**Issue by adombrovsky** [Maks3w/SwaggerAssertions#47]
These two methods have different implementation and it affects some cases, for example when you try to test endpoint with query parameters. When URI has query parameters The assertRequestMatch succeeded, but assertResponseMatch fails, because they use different values for $path variable:
assertRequestMatch - $request->getPathInfo()
assertResponseMatch - $request->getRequestUri()

Can you confirm that it has been implemented in this way intentionally?

**Comment by Maks3w** [comment]
If you think you have find a problem please open a PR with a test and the proposed fix.
