### ISSUE TITLE
SchemaStorage::expandRefs() loops infinitely on recursive $ref definition

### ISSUE THREAD

**Issue by MaikWagner** [Maks3w/SwaggerAssertions#53]
Hi,

I was trying to validate a response with a json schema that has circular $ref definitions. This is basically allowed (https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-7) but leads to an php error after looping infinitely:

> PHP Fatal error:  Maximum execution time of 30 seconds exceeded in vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php on line 85

With xdebug enabled it exits after a while and throws this backtrace:

> PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php:86
Stack trace:
#0 vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(86): is_object('id')
#1 vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(89): JsonSchema\SchemaStorage->expandRefs('id', 'internal://prov...')
#2 vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(107): JsonSchema\SchemaStorage->expandRefs(Array, 'internal://prov...')
#3 vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(107): JsonSchema\SchemaStorage->expandRefs(Object(stdClass), 'internal://prov...')
#4 vendor/justinrainbow/json-schema/src/JsonSchema/SchemaSto in vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php on line 86

<img width="448" alt="schema-loop-debug" src="https://user-images.githubusercontent.com/7701966/44721673-f4ae9d00-aaca-11e8-85e9-f077e215fb17.png">

You can reproduce the issue with the following code:

**test.php**
```<?php
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/Response.php';
require_once __DIR__ . '/SwaggerSchemaManager.php';
require_once __DIR__ . '/SwaggerValidator.php';
require_once __DIR__ . '/Validator.php';

$definition =  __DIR__ . '/swagger.json';
if (!is_readable($definition)) {
        throw new Exception("Could not read '$definition'.");
}

//$header = getHeader((array) ([]));
//$body = $filename === '' ? '' : readFromFile($filename);
$response = new Response(200, [], "", "/ps?hash=123", 'GET');

$validator = new SwaggerValidator('file://' . $definition);

if ($result = $validator->validateResponse($response)) {
        print("ok\n");
} else {
        fprintf(STDERR, implode(', ', $validator->getErrors()) . "\n");
        exit(1);
}
```

**swagger.json**
```
{
  "swagger": "2.0",
  "info": {
    "title": "Test",
    "version": "0.0.1"
  },
  "paths": {
    "/ps": {
      "get": {
        "parameters": [
          {
            "in": "query",
            "name": "hash",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "foo",
            "schema": {
              "$ref": "#/definitions/actionItem"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "response": {
    },
    "actionItem": {
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "refs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/actionItem"
          }
        }
      }
    }
  }
}
```

**Comment by Maks3w** [comment]
Feel free to open the issue to the justinrainbow/json-schema project.

Alternative, you can instantiate the SchemaManager with a full schema (with resolved references) using the constructor https://github.com/Maks3w/SwaggerAssertions/blob/master/src/SchemaManager.php#L40
